# Generated by Django 5.0.6 on 2024-07-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='foto',
            field=models.ImageField(default='ninguno', upload_to=''),
        ),
    ]
